version: 0.2
phases:
  pre_build:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i npm@latest -g
      - npm cache clean --force
      - rm -rf node_modules package-lock.json
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - build/**/*
  
